### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Moneylover3246** [popstarfreas/dimensions-mcl#1]
My cmd recognizes that the plugin is  in use. However every time I attemot to join from mobile, it doesn't work. I have the 5.7.0 and 1.5.0 dimensions, my pirts are forwarded, my config.js is configured, but I don't know what's wrong

**Comment by popstarfreas** [comment]
Dimensions v5.7.0 is for Terraria v1.3.5.3
Dimensions v5.8.3 is for Terraria v1.4.0.1 and greater

The current version of MCL is only compatible with v5.7.0 and Terraria v1.3.5.3. Is this what you are testing?

**Comment by Moneylover3246** [comment]
Yes I'm using 1.3.5.3, however it just isn't working for whatever reason

**Comment by popstarfreas** [comment]
Any more information about what happens when you are trying to join?

**Comment by Moneylover3246** [comment]
When I try to join from the listen port (9999 in my case,) it doesnt work at all. When I join from the server port (9998) I get the Legacy Message. For my configs, they're all the way they're supposed to be.  I don't know how to use GitHub very well. But if DMs exist, I could send you a screenshot of the configs

**Comment by popstarfreas** [comment]
I assume you're using this to bridge PC and Mobile? Are you able to join the listen port on PC?

**Comment by Moneylover3246** [comment]
I haven't checked yet. Let me go see now

**Comment by Moneylover3246** [comment]
Actually I realized I can't do that because my tshock is on 1.3.5.3

**Comment by popstarfreas** [comment]
What's your reason for trying to use MCL?

**Comment by Moneylover3246** [comment]
PC-Mobile bridge

**Comment by popstarfreas** [comment]
Are you aware of another option: using PC version 1.3.0.7 (or was it 1.3.0.8) and running either a 1.3 server or using the mobile server? I've not tried it myself but I heard it mentioned.

MCL is mainly for PC servers that want to accept mobile players as well, with the knowledge that some features don't exist on mobile yet. How do you expect PC players to play? By using specifically 1.3.5.3?

**Comment by Moneylover3246** [comment]
I just want to use this plugin so I can use a PC tshock version. The mobile version doesn't support plugins so thats the main reason I'm here. Im going to try to use the 1.3.0.7.tshock and see how it goes

**Comment by Moneylover3246** [comment]
I tried to download the tshock. I always get an error when I try to launch the server. It says the following: [Server API] Error Server crashed due to an unhandled exception:
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComparer`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.Main.LoadWorlds()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)

Can you please tell me how to fix this?

**Comment by popstarfreas** [comment]
You must have incompatible worlds in your worlds folder.

**Comment by Moneylover3246** [comment]
Are you talking about the worlds folder on my actual terraria? Typically for tshock on mobile the worlds folder is stored in the actual tshock plugin.

**Comment by Moneylover3246** [comment]
Well the error resolved after deleting the 1.3.5 worlds. However using a pc world for mobile doesn't work because when I join it keeps crashing. Can you figure out how I can fix the PC-Mobile bridge not working?

**Comment by Moneylover3246** [comment]
Idk if github supports dms but I was wondering if we can go on a dm supporting website like discord (If you have it/ want to do it) and if you can just tell me step by step on how to make this plugin work.

**Comment by popstarfreas** [comment]
I don't know, I've never done it. My expertise is in compatibility with the current PC version, not old PC versions.

**Comment by Moneylover3246** [comment]
Well I was actually just about to create a PC server for 1.4. Can you tell me how to do that?
